### ISSUE TITLE
Hands-on with pprof.

### ISSUE THREAD

**Issue by ankur-anand** [go-study-group/agendas#11]
# I'd Like To Learn Something

Hands-on with pprof

Note: Moving the Request from Google Documents agenda.

**Comment by corylanou** [comment]
I'd be happy to present a module on this.  I have all the material from training.  basic pprof, flame graphs, etc.  Let me know if there is anything specific.  I'm happy to go over the material ahead of time with the group as well if there are any questions on the content.

**Comment by ankur-anand** [comment]
@corylanou That would be awesome. 😃

**Comment by ankur-anand** [comment]
Video session available here https://youtu.be/YNye3SZWvj8
