### ISSUE TITLE
How to Test Drive integrating with the YouTube Data API

### ISSUE THREAD

**Issue by pdt256** [go-study-group/agendas#3]
# YouTube Data API Integration

We will explore how to create maintainable 3rd party API integrations. We will create a command line Go application to upload a video using the Youtube Data API.

Goals:

- See Top Down Design and Test Driven Development in action!
- Learn how to structure a simple Go command line application
- Leverage Go 1.11 Modules
- Understand the JetBrains GoLand IDE tooling
  - TDD
  - Refactoring
  - Git Integration
  - gofmt
- Create a pull request: https://github.com/go-study-group/videos

**Comment by arschles** [comment]
I ❤️ this. right now, I have a lot of manual work to download study group recordings from the zoom site and upload them to the youtube channel. this is 1/2 of the solution!!!

@pdt256 can you let me know when is a good time in the near-ish future that you can show this?

**Comment by arschles** [comment]
Related to #2

**Comment by arschles** [comment]
@pdt256 I've created, and we can put your code in there as you write it 😄

**Comment by pdt256** [comment]
I am available Thursday, November 1st. We can walk through writing the code from scratch. It should take around 30 minutes.

**Comment by arschles** [comment]
@pdt256 showed the code and submitted a PR for it. Thanks Jamie! https://github.com/go-study-group/videos/pull/2
