### ISSUE TITLE
Building a simple blockchain in go

### ISSUE THREAD

**Issue by cchx0000** [go-study-group/agendas#5]
I want to walk over the steps required to build a simple blockchain with p2p, rpc and etc

**Comment by arschles** [comment]
@cchx0000 great! I'm going to schedule you for next week, November 8, 2018

**Comment by arschles** [comment]
@cchx0000 will be starting with [this post](https://medium.com/@mycoralhealth/code-a-simple-p2p-blockchain-in-go-46662601f417). It's not completely working so he's going to be doing a lot of work today to fix it.

**Comment by arschles** [comment]
A few important concepts:

- Cosensus across a distributed network
- Proof of work
- Decentralization

He'll be using the go-libp2p library

**Comment by arschles** [comment]
Here's the libp2p website: https://libp2p.io/

And here's a cool implementation using it: https://ipfs.io/

**Comment by arschles** [comment]
Regarding IPFS, CloudFlare has a really cool way to serve IPFS files over HTTP: https://blog.cloudflare.com/distributed-web-gateway

**Comment by arschles** [comment]
Thanks again @cchx0000!
